### ISSUE TITLE
Add subscription badge to messages

### ISSUE THREAD

**Issue by RomainLanz** [Streali/App#157]

**Comment by nicolas-besnard** [comment]
Hello 👋 If you want to display the streamer's badge, you'll first need to do an API call to Twitch's API, so it would need to be a back-end thing.

https://dev.twitch.tv/docs/api/reference#get-channel-chat-badges

Then, using TMI.js, the `tags.badges` will contain a "premium" with the number of months you subscribed

**Comment by RomainLanz** [comment]
Done.
