### ISSUE TITLE
Refresh human timestamp on the event list

### ISSUE THREAD

**Issue by RomainLanz** [Streali/App#170]
Currently, the timestamp is only updated when a new event arrived.
Making it useless for the streamer.

![](https://user-images.githubusercontent.com/2793951/210642565-323ae392-104e-4a40-be0f-f26d3649f876.png)

**Comment by nicolas-besnard** [comment]
Hi @RomainLanz, what approach would you recommend? I can see 2:

1. in `src/components/event/event.tsx`, add a `useEffect` with a timeout to refresh the date string
2. in `src/pages/events.tsx`, add a `useEffect` to add a new key like `humanCreatedAt` and refresh all events every X minutes

For the first approach, that would be easy to implement there will be a lot of `setInterval`

For the second approach, it would require to change the `EventSchema` defined [here](https://github.com/Streali/App/blob/staging/src/types/schemas/event.ts#L118) to add a new key. 

This adds the question of how do you want to handle adding new keys to a schema for UI purposes only.

If you had any other approach in mind, let me know :)

**Comment by RomainLanz** [comment]
I prefer the second options, which would avoid creating X amount of Timer in the browser (one for each event).

We don't need to modify the schema to make that work.
We can create one timer in `src/pages/events.tsx` that sets a `key` attribute to re-render the whole list.

Something like this:
```tsx
function Events() {
  const [renderKey, setRenderKey] = useState(Date.now)

  useEffect(() => {
    const timer = setTimeout(() => setRenderKey(Date.now), 1000 * 60)

    return clearTimeout(timer)
  })

  return (
    ...
  )
}
```

**Comment by nicolas-besnard** [comment]
That would work too! Aren't you concerned about re-rendering potentially thousands of rows every minute? I'll update my PR :)

**Comment by RomainLanz** [comment]
> That would work too! Aren't you concerned about re-rendering potentially thousands of rows every minute? I'll update my PR :)

Nevertheless, we will have to re-render X components. The only difference is not having a lot of `setTimeout` defined.
We are also going to limit the number of events stored/returned. The performance will not be an issue. 👍🏻
