### ISSUE TITLE
Add an attribute to set a default value to an input

### ISSUE THREAD

**Issue by JeremLopes** [Streali/App#182]
**Is your feature request related to a problem? Please describe.**
I can't put a default value to an input.

**Describe the solution you'd like**
Add an attribute `value` to set a default value to an input.

**Comment by WilliamTraoreee** [comment]
Hi @JeremLopes !

Like I said on  your PR, we already can add a default value on a input with the props `defaultValue`. We extends the component props with the default input one to add props like `defaultValue` or `onClick` for exemple.
