### ISSUE TITLE
Remove MinWidthWindow and LoginPage on embed

### ISSUE THREAD

**Issue by WilliamTraoreee** [Streali/App#72]
**Describe the bug**
Actually if we had the embed chat on OBS, we have this behavior

![image](https://user-images.githubusercontent.com/33811490/192767795-de0249d9-1216-48c8-8771-5988bdbf8337.png)

**Expected behavior**
- Remove `MinWidthWindow` on embed (you can add the component on the `noLayout`)
- Remove the embed page of the protected route

**Comment by RomainLanz** [comment]
Linked PR only removes the `<MinWidthWindow />` component on the embed routes.
The issue of required login page is still present.
