### ISSUE TITLE
Wrong value in default padding

### ISSUE THREAD

**Issue by WilliamTraoreee** [Streali/App#73]
**Describe the bug**
When we edit a chat theme, we don't have the correct value on vertical/horizontal input.

**To Reproduce**

1. Create a chat theme
2. Add outer padding on `Name`
3. Edit it
4. Go on `Name` > `Outer padding`

**Expected behavior**
Retrieve the correct value on horizontal/vertical input
Change the icon of horizontal

**Comment by AntoineHbnt** [comment]
I'm working on it
